/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnaliseFaturamentoRouteImport } from './routes/analise-faturamento'
import { Route as BasePrecificacaoRouteImport } from './routes/base-precificacao'
import { Route as ContratosRouteImport } from './routes/contratos'
import { Route as ContratosTesteRouteImport } from './routes/contratos-teste'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as DesignSystemIconesRouteImport } from './routes/design-system-icones'
import { Route as TussRouteImport } from './routes/tuss'
import { Route as AnaliseFaturamentoAnalysisIdRouteImport } from './routes/analise-faturamento_.$analysisId'
import { Route as BasePrecificacaoVersionIdRouteImport } from './routes/base-precificacao_.$versionId'
import { Route as ContratosTesteOperatorIdRouteImport } from './routes/contratos-teste_.$operatorId'
import { Route as ContratosContractIdRouteImport } from './routes/contratos_.$contractId'
import { Route as AnaliseFaturamentoAnalysisIdResultadoRouteImport } from './routes/analise-faturamento_.$analysisId_.resultado'
import { Route as ContratosContractIdExtracaoFileIdRouteImport } from './routes/contratos_.$contractId_.extracao.$fileId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnaliseFaturamentoRoute = AnaliseFaturamentoRouteImport.update({
  id: '/analise-faturamento',
  path: '/analise-faturamento',
  getParentRoute: () => rootRouteImport,
} as any)
const BasePrecificacaoRoute = BasePrecificacaoRouteImport.update({
  id: '/base-precificacao',
  path: '/base-precificacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratosRoute = ContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratosTesteRoute = ContratosTesteRouteImport.update({
  id: '/contratos-teste',
  path: '/contratos-teste',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemIconesRoute = DesignSystemIconesRouteImport.update({
  id: '/design-system-icones',
  path: '/design-system-icones',
  getParentRoute: () => rootRouteImport,
} as any)
const TussRoute = TussRouteImport.update({
  id: '/tuss',
  path: '/tuss',
  getParentRoute: () => rootRouteImport,
} as any)
const AnaliseFaturamentoAnalysisIdRoute =
  AnaliseFaturamentoAnalysisIdRouteImport.update({
    id: '/analise-faturamento_/$analysisId',
    path: '/analise-faturamento/$analysisId',
    getParentRoute: () => rootRouteImport,
  } as any)
const BasePrecificacaoVersionIdRoute =
  BasePrecificacaoVersionIdRouteImport.update({
    id: '/base-precificacao_/$versionId',
    path: '/base-precificacao/$versionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContratosTesteOperatorIdRoute =
  ContratosTesteOperatorIdRouteImport.update({
    id: '/contratos-teste_/$operatorId',
    path: '/contratos-teste/$operatorId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContratosContractIdRoute = ContratosContractIdRouteImport.update({
  id: '/contratos_/$contractId',
  path: '/contratos/$contractId',
  getParentRoute: () => rootRouteImport,
} as any)
const AnaliseFaturamentoAnalysisIdResultadoRoute =
  AnaliseFaturamentoAnalysisIdResultadoRouteImport.update({
    id: '/analise-faturamento_/$analysisId_/resultado',
    path: '/analise-faturamento/$analysisId/resultado',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContratosContractIdExtracaoFileIdRoute =
  ContratosContractIdExtracaoFileIdRouteImport.update({
    id: '/contratos_/$contractId_/extracao/$fileId',
    path: '/contratos/$contractId/extracao/$fileId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analise-faturamento': typeof AnaliseFaturamentoRoute
  '/base-precificacao': typeof BasePrecificacaoRoute
  '/contratos': typeof ContratosRoute
  '/contratos-teste': typeof ContratosTesteRoute
  '/design-system': typeof DesignSystemRoute
  '/design-system-icones': typeof DesignSystemIconesRoute
  '/tuss': typeof TussRoute
  '/analise-faturamento/$analysisId': typeof AnaliseFaturamentoAnalysisIdRoute
  '/base-precificacao/$versionId': typeof BasePrecificacaoVersionIdRoute
  '/contratos-teste/$operatorId': typeof ContratosTesteOperatorIdRoute
  '/contratos/$contractId': typeof ContratosContractIdRoute
  '/analise-faturamento/$analysisId/resultado': typeof AnaliseFaturamentoAnalysisIdResultadoRoute
  '/contratos/$contractId/extracao/$fileId': typeof ContratosContractIdExtracaoFileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analise-faturamento': typeof AnaliseFaturamentoRoute
  '/base-precificacao': typeof BasePrecificacaoRoute
  '/contratos': typeof ContratosRoute
  '/contratos-teste': typeof ContratosTesteRoute
  '/design-system': typeof DesignSystemRoute
  '/design-system-icones': typeof DesignSystemIconesRoute
  '/tuss': typeof TussRoute
  '/analise-faturamento/$analysisId': typeof AnaliseFaturamentoAnalysisIdRoute
  '/base-precificacao/$versionId': typeof BasePrecificacaoVersionIdRoute
  '/contratos-teste/$operatorId': typeof ContratosTesteOperatorIdRoute
  '/contratos/$contractId': typeof ContratosContractIdRoute
  '/analise-faturamento/$analysisId/resultado': typeof AnaliseFaturamentoAnalysisIdResultadoRoute
  '/contratos/$contractId/extracao/$fileId': typeof ContratosContractIdExtracaoFileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analise-faturamento': typeof AnaliseFaturamentoRoute
  '/base-precificacao': typeof BasePrecificacaoRoute
  '/contratos': typeof ContratosRoute
  '/contratos-teste': typeof ContratosTesteRoute
  '/design-system': typeof DesignSystemRoute
  '/design-system-icones': typeof DesignSystemIconesRoute
  '/tuss': typeof TussRoute
  '/analise-faturamento_/$analysisId': typeof AnaliseFaturamentoAnalysisIdRoute
  '/base-precificacao_/$versionId': typeof BasePrecificacaoVersionIdRoute
  '/contratos-teste_/$operatorId': typeof ContratosTesteOperatorIdRoute
  '/contratos_/$contractId': typeof ContratosContractIdRoute
  '/analise-faturamento_/$analysisId_/resultado': typeof AnaliseFaturamentoAnalysisIdResultadoRoute
  '/contratos_/$contractId_/extracao/$fileId': typeof ContratosContractIdExtracaoFileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analise-faturamento'
    | '/base-precificacao'
    | '/contratos'
    | '/contratos-teste'
    | '/design-system'
    | '/design-system-icones'
    | '/tuss'
    | '/analise-faturamento/$analysisId'
    | '/base-precificacao/$versionId'
    | '/contratos-teste/$operatorId'
    | '/contratos/$contractId'
    | '/analise-faturamento/$analysisId/resultado'
    | '/contratos/$contractId/extracao/$fileId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analise-faturamento'
    | '/base-precificacao'
    | '/contratos'
    | '/contratos-teste'
    | '/design-system'
    | '/design-system-icones'
    | '/tuss'
    | '/analise-faturamento/$analysisId'
    | '/base-precificacao/$versionId'
    | '/contratos-teste/$operatorId'
    | '/contratos/$contractId'
    | '/analise-faturamento/$analysisId/resultado'
    | '/contratos/$contractId/extracao/$fileId'
  id:
    | '__root__'
    | '/'
    | '/analise-faturamento'
    | '/base-precificacao'
    | '/contratos'
    | '/contratos-teste'
    | '/design-system'
    | '/design-system-icones'
    | '/tuss'
    | '/analise-faturamento_/$analysisId'
    | '/base-precificacao_/$versionId'
    | '/contratos-teste_/$operatorId'
    | '/contratos_/$contractId'
    | '/analise-faturamento_/$analysisId_/resultado'
    | '/contratos_/$contractId_/extracao/$fileId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnaliseFaturamentoRoute: typeof AnaliseFaturamentoRoute
  BasePrecificacaoRoute: typeof BasePrecificacaoRoute
  ContratosRoute: typeof ContratosRoute
  ContratosTesteRoute: typeof ContratosTesteRoute
  DesignSystemRoute: typeof DesignSystemRoute
  DesignSystemIconesRoute: typeof DesignSystemIconesRoute
  TussRoute: typeof TussRoute
  AnaliseFaturamentoAnalysisIdRoute: typeof AnaliseFaturamentoAnalysisIdRoute
  BasePrecificacaoVersionIdRoute: typeof BasePrecificacaoVersionIdRoute
  ContratosTesteOperatorIdRoute: typeof ContratosTesteOperatorIdRoute
  ContratosContractIdRoute: typeof ContratosContractIdRoute
  AnaliseFaturamentoAnalysisIdResultadoRoute: typeof AnaliseFaturamentoAnalysisIdResultadoRoute
  ContratosContractIdExtracaoFileIdRoute: typeof ContratosContractIdExtracaoFileIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analise-faturamento': {
      id: '/analise-faturamento'
      path: '/analise-faturamento'
      fullPath: '/analise-faturamento'
      preLoaderRoute: typeof AnaliseFaturamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base-precificacao': {
      id: '/base-precificacao'
      path: '/base-precificacao'
      fullPath: '/base-precificacao'
      preLoaderRoute: typeof BasePrecificacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contratos': {
      id: '/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof ContratosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contratos-teste': {
      id: '/contratos-teste'
      path: '/contratos-teste'
      fullPath: '/contratos-teste'
      preLoaderRoute: typeof ContratosTesteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system-icones': {
      id: '/design-system-icones'
      path: '/design-system-icones'
      fullPath: '/design-system-icones'
      preLoaderRoute: typeof DesignSystemIconesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tuss': {
      id: '/tuss'
      path: '/tuss'
      fullPath: '/tuss'
      preLoaderRoute: typeof TussRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analise-faturamento_/$analysisId': {
      id: '/analise-faturamento_/$analysisId'
      path: '/analise-faturamento/$analysisId'
      fullPath: '/analise-faturamento/$analysisId'
      preLoaderRoute: typeof AnaliseFaturamentoAnalysisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base-precificacao_/$versionId': {
      id: '/base-precificacao_/$versionId'
      path: '/base-precificacao/$versionId'
      fullPath: '/base-precificacao/$versionId'
      preLoaderRoute: typeof BasePrecificacaoVersionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contratos-teste_/$operatorId': {
      id: '/contratos-teste_/$operatorId'
      path: '/contratos-teste/$operatorId'
      fullPath: '/contratos-teste/$operatorId'
      preLoaderRoute: typeof ContratosTesteOperatorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contratos_/$contractId': {
      id: '/contratos_/$contractId'
      path: '/contratos/$contractId'
      fullPath: '/contratos/$contractId'
      preLoaderRoute: typeof ContratosContractIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analise-faturamento_/$analysisId_/resultado': {
      id: '/analise-faturamento_/$analysisId_/resultado'
      path: '/analise-faturamento/$analysisId/resultado'
      fullPath: '/analise-faturamento/$analysisId/resultado'
      preLoaderRoute: typeof AnaliseFaturamentoAnalysisIdResultadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contratos_/$contractId_/extracao/$fileId': {
      id: '/contratos_/$contractId_/extracao/$fileId'
      path: '/contratos/$contractId/extracao/$fileId'
      fullPath: '/contratos/$contractId/extracao/$fileId'
      preLoaderRoute: typeof ContratosContractIdExtracaoFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnaliseFaturamentoRoute: AnaliseFaturamentoRoute,
  BasePrecificacaoRoute: BasePrecificacaoRoute,
  ContratosRoute: ContratosRoute,
  ContratosTesteRoute: ContratosTesteRoute,
  DesignSystemRoute: DesignSystemRoute,
  DesignSystemIconesRoute: DesignSystemIconesRoute,
  TussRoute: TussRoute,
  AnaliseFaturamentoAnalysisIdRoute: AnaliseFaturamentoAnalysisIdRoute,
  BasePrecificacaoVersionIdRoute: BasePrecificacaoVersionIdRoute,
  ContratosTesteOperatorIdRoute: ContratosTesteOperatorIdRoute,
  ContratosContractIdRoute: ContratosContractIdRoute,
  AnaliseFaturamentoAnalysisIdResultadoRoute:
    AnaliseFaturamentoAnalysisIdResultadoRoute,
  ContratosContractIdExtracaoFileIdRoute:
    ContratosContractIdExtracaoFileIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
