/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContratosRouteImport } from './routes/contratos'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as DesignSystemIconesRouteImport } from './routes/design-system-icones'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratosRoute = ContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemIconesRoute = DesignSystemIconesRouteImport.update({
  id: '/design-system-icones',
  path: '/design-system-icones',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contratos': typeof ContratosRoute
  '/design-system': typeof DesignSystemRoute
  '/design-system-icones': typeof DesignSystemIconesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contratos': typeof ContratosRoute
  '/design-system': typeof DesignSystemRoute
  '/design-system-icones': typeof DesignSystemIconesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contratos': typeof ContratosRoute
  '/design-system': typeof DesignSystemRoute
  '/design-system-icones': typeof DesignSystemIconesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contratos' | '/design-system' | '/design-system-icones'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contratos' | '/design-system' | '/design-system-icones'
  id:
    | '__root__'
    | '/'
    | '/contratos'
    | '/design-system'
    | '/design-system-icones'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContratosRoute: typeof ContratosRoute
  DesignSystemRoute: typeof DesignSystemRoute
  DesignSystemIconesRoute: typeof DesignSystemIconesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contratos': {
      id: '/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof ContratosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system-icones': {
      id: '/design-system-icones'
      path: '/design-system-icones'
      fullPath: '/design-system-icones'
      preLoaderRoute: typeof DesignSystemIconesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContratosRoute: ContratosRoute,
  DesignSystemRoute: DesignSystemRoute,
  DesignSystemIconesRoute: DesignSystemIconesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
