/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnaliseFaturamentoRouteImport } from './routes/analise-faturamento'
import { Route as BasePrecificacaoRouteImport } from './routes/base-precificacao'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as DesignSystemIconesRouteImport } from './routes/design-system-icones'
import { Route as OperadorasRouteImport } from './routes/operadoras'
import { Route as TussRouteImport } from './routes/tuss'
import { Route as AnaliseFaturamentoAnalysisIdRouteImport } from './routes/analise-faturamento_.$analysisId'
import { Route as BasePrecificacaoVersionIdRouteImport } from './routes/base-precificacao_.$versionId'
import { Route as OperadorasContractIdRouteImport } from './routes/operadoras_.$contractId'
import { Route as AnaliseFaturamentoAnalysisIdResultadoRouteImport } from './routes/analise-faturamento_.$analysisId_.resultado'
import { Route as OperadorasContractIdExtracaoFileIdRouteImport } from './routes/operadoras_.$contractId_.extracao.$fileId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnaliseFaturamentoRoute = AnaliseFaturamentoRouteImport.update({
  id: '/analise-faturamento',
  path: '/analise-faturamento',
  getParentRoute: () => rootRouteImport,
} as any)
const BasePrecificacaoRoute = BasePrecificacaoRouteImport.update({
  id: '/base-precificacao',
  path: '/base-precificacao',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemIconesRoute = DesignSystemIconesRouteImport.update({
  id: '/design-system-icones',
  path: '/design-system-icones',
  getParentRoute: () => rootRouteImport,
} as any)
const OperadorasRoute = OperadorasRouteImport.update({
  id: '/operadoras',
  path: '/operadoras',
  getParentRoute: () => rootRouteImport,
} as any)
const TussRoute = TussRouteImport.update({
  id: '/tuss',
  path: '/tuss',
  getParentRoute: () => rootRouteImport,
} as any)
const AnaliseFaturamentoAnalysisIdRoute =
  AnaliseFaturamentoAnalysisIdRouteImport.update({
    id: '/analise-faturamento_/$analysisId',
    path: '/analise-faturamento/$analysisId',
    getParentRoute: () => rootRouteImport,
  } as any)
const BasePrecificacaoVersionIdRoute =
  BasePrecificacaoVersionIdRouteImport.update({
    id: '/base-precificacao_/$versionId',
    path: '/base-precificacao/$versionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const OperadorasContractIdRoute = OperadorasContractIdRouteImport.update({
  id: '/operadoras_/$contractId',
  path: '/operadoras/$contractId',
  getParentRoute: () => rootRouteImport,
} as any)
const AnaliseFaturamentoAnalysisIdResultadoRoute =
  AnaliseFaturamentoAnalysisIdResultadoRouteImport.update({
    id: '/analise-faturamento_/$analysisId_/resultado',
    path: '/analise-faturamento/$analysisId/resultado',
    getParentRoute: () => rootRouteImport,
  } as any)
const OperadorasContractIdExtracaoFileIdRoute =
  OperadorasContractIdExtracaoFileIdRouteImport.update({
    id: '/operadoras_/$contractId_/extracao/$fileId',
    path: '/operadoras/$contractId/extracao/$fileId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analise-faturamento': typeof AnaliseFaturamentoRoute
  '/base-precificacao': typeof BasePrecificacaoRoute
  '/design-system': typeof DesignSystemRoute
  '/design-system-icones': typeof DesignSystemIconesRoute
  '/operadoras': typeof OperadorasRoute
  '/tuss': typeof TussRoute
  '/analise-faturamento/$analysisId': typeof AnaliseFaturamentoAnalysisIdRoute
  '/base-precificacao/$versionId': typeof BasePrecificacaoVersionIdRoute
  '/operadoras/$contractId': typeof OperadorasContractIdRoute
  '/analise-faturamento/$analysisId/resultado': typeof AnaliseFaturamentoAnalysisIdResultadoRoute
  '/operadoras/$contractId/extracao/$fileId': typeof OperadorasContractIdExtracaoFileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analise-faturamento': typeof AnaliseFaturamentoRoute
  '/base-precificacao': typeof BasePrecificacaoRoute
  '/design-system': typeof DesignSystemRoute
  '/design-system-icones': typeof DesignSystemIconesRoute
  '/operadoras': typeof OperadorasRoute
  '/tuss': typeof TussRoute
  '/analise-faturamento/$analysisId': typeof AnaliseFaturamentoAnalysisIdRoute
  '/base-precificacao/$versionId': typeof BasePrecificacaoVersionIdRoute
  '/operadoras/$contractId': typeof OperadorasContractIdRoute
  '/analise-faturamento/$analysisId/resultado': typeof AnaliseFaturamentoAnalysisIdResultadoRoute
  '/operadoras/$contractId/extracao/$fileId': typeof OperadorasContractIdExtracaoFileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analise-faturamento': typeof AnaliseFaturamentoRoute
  '/base-precificacao': typeof BasePrecificacaoRoute
  '/design-system': typeof DesignSystemRoute
  '/design-system-icones': typeof DesignSystemIconesRoute
  '/operadoras': typeof OperadorasRoute
  '/tuss': typeof TussRoute
  '/analise-faturamento_/$analysisId': typeof AnaliseFaturamentoAnalysisIdRoute
  '/base-precificacao_/$versionId': typeof BasePrecificacaoVersionIdRoute
  '/operadoras_/$contractId': typeof OperadorasContractIdRoute
  '/analise-faturamento_/$analysisId_/resultado': typeof AnaliseFaturamentoAnalysisIdResultadoRoute
  '/operadoras_/$contractId_/extracao/$fileId': typeof OperadorasContractIdExtracaoFileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analise-faturamento'
    | '/base-precificacao'
    | '/design-system'
    | '/design-system-icones'
    | '/operadoras'
    | '/tuss'
    | '/analise-faturamento/$analysisId'
    | '/base-precificacao/$versionId'
    | '/operadoras/$contractId'
    | '/analise-faturamento/$analysisId/resultado'
    | '/operadoras/$contractId/extracao/$fileId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analise-faturamento'
    | '/base-precificacao'
    | '/design-system'
    | '/design-system-icones'
    | '/operadoras'
    | '/tuss'
    | '/analise-faturamento/$analysisId'
    | '/base-precificacao/$versionId'
    | '/operadoras/$contractId'
    | '/analise-faturamento/$analysisId/resultado'
    | '/operadoras/$contractId/extracao/$fileId'
  id:
    | '__root__'
    | '/'
    | '/analise-faturamento'
    | '/base-precificacao'
    | '/design-system'
    | '/design-system-icones'
    | '/operadoras'
    | '/tuss'
    | '/analise-faturamento_/$analysisId'
    | '/base-precificacao_/$versionId'
    | '/operadoras_/$contractId'
    | '/analise-faturamento_/$analysisId_/resultado'
    | '/operadoras_/$contractId_/extracao/$fileId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnaliseFaturamentoRoute: typeof AnaliseFaturamentoRoute
  BasePrecificacaoRoute: typeof BasePrecificacaoRoute
  DesignSystemRoute: typeof DesignSystemRoute
  DesignSystemIconesRoute: typeof DesignSystemIconesRoute
  OperadorasRoute: typeof OperadorasRoute
  TussRoute: typeof TussRoute
  AnaliseFaturamentoAnalysisIdRoute: typeof AnaliseFaturamentoAnalysisIdRoute
  BasePrecificacaoVersionIdRoute: typeof BasePrecificacaoVersionIdRoute
  OperadorasContractIdRoute: typeof OperadorasContractIdRoute
  AnaliseFaturamentoAnalysisIdResultadoRoute: typeof AnaliseFaturamentoAnalysisIdResultadoRoute
  OperadorasContractIdExtracaoFileIdRoute: typeof OperadorasContractIdExtracaoFileIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analise-faturamento': {
      id: '/analise-faturamento'
      path: '/analise-faturamento'
      fullPath: '/analise-faturamento'
      preLoaderRoute: typeof AnaliseFaturamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base-precificacao': {
      id: '/base-precificacao'
      path: '/base-precificacao'
      fullPath: '/base-precificacao'
      preLoaderRoute: typeof BasePrecificacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system-icones': {
      id: '/design-system-icones'
      path: '/design-system-icones'
      fullPath: '/design-system-icones'
      preLoaderRoute: typeof DesignSystemIconesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operadoras': {
      id: '/operadoras'
      path: '/operadoras'
      fullPath: '/operadoras'
      preLoaderRoute: typeof OperadorasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tuss': {
      id: '/tuss'
      path: '/tuss'
      fullPath: '/tuss'
      preLoaderRoute: typeof TussRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analise-faturamento_/$analysisId': {
      id: '/analise-faturamento_/$analysisId'
      path: '/analise-faturamento/$analysisId'
      fullPath: '/analise-faturamento/$analysisId'
      preLoaderRoute: typeof AnaliseFaturamentoAnalysisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base-precificacao_/$versionId': {
      id: '/base-precificacao_/$versionId'
      path: '/base-precificacao/$versionId'
      fullPath: '/base-precificacao/$versionId'
      preLoaderRoute: typeof BasePrecificacaoVersionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operadoras_/$contractId': {
      id: '/operadoras_/$contractId'
      path: '/operadoras/$contractId'
      fullPath: '/operadoras/$contractId'
      preLoaderRoute: typeof OperadorasContractIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analise-faturamento_/$analysisId_/resultado': {
      id: '/analise-faturamento_/$analysisId_/resultado'
      path: '/analise-faturamento/$analysisId/resultado'
      fullPath: '/analise-faturamento/$analysisId/resultado'
      preLoaderRoute: typeof AnaliseFaturamentoAnalysisIdResultadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operadoras_/$contractId_/extracao/$fileId': {
      id: '/operadoras_/$contractId_/extracao/$fileId'
      path: '/operadoras/$contractId/extracao/$fileId'
      fullPath: '/operadoras/$contractId/extracao/$fileId'
      preLoaderRoute: typeof OperadorasContractIdExtracaoFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnaliseFaturamentoRoute: AnaliseFaturamentoRoute,
  BasePrecificacaoRoute: BasePrecificacaoRoute,
  DesignSystemRoute: DesignSystemRoute,
  DesignSystemIconesRoute: DesignSystemIconesRoute,
  OperadorasRoute: OperadorasRoute,
  TussRoute: TussRoute,
  AnaliseFaturamentoAnalysisIdRoute: AnaliseFaturamentoAnalysisIdRoute,
  BasePrecificacaoVersionIdRoute: BasePrecificacaoVersionIdRoute,
  OperadorasContractIdRoute: OperadorasContractIdRoute,
  AnaliseFaturamentoAnalysisIdResultadoRoute:
    AnaliseFaturamentoAnalysisIdResultadoRoute,
  OperadorasContractIdExtracaoFileIdRoute:
    OperadorasContractIdExtracaoFileIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
